language: c

os: linux

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libudev-dev
    - git clone git://github.com/signal11/hidapi.git
    - cd hidapi && sh bootstrap && sh configure && make && sudo make install

script:
    - make

after_success:
    - bash <(curl -s https://codecov.io/bash)
