name: rahhid

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install \
               build-essential \
               libhidapi-dev
      - name: clean
        run: make clean
      - name: make
        run: make
  macos:
    name: macos
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: brew bundle
        run: brew bundle
      - name: clean
        run: make clean
      - name: make
        run: make
